import { EntityRepository, Repository } from 'typeorm';
import { AuthCredentialsDto } from './dto/auth-credentials.dto';
import { User } from './user.entity';

@EntityRepository(User)
export class UsersRepository extends Repository<User> {
  /**
   * Takes the user details, creates a new user and saves the user in the database
   *
   * @param {AuthCredentialsDto} authCredentialDto
   * @return {*}  {Promise<void>}
   * @memberof UsersRepository
   */
  async createUser(authCredentialDto: AuthCredentialsDto): Promise<void> {
    const { username, password } = authCredentialDto;

    const user = this.create({
      // Do not specify id because in the Entity the id is automatically generated by typeorm with uuid
      username,
      password,
    });

    await this.save(user);
  }
}
